# Generated by Django 2.1.3 on 2018-11-03 10:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ater_img',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_img, verbose_name='头像'),
        ),
    ]
