# Generated by Django 2.1.3 on 2019-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181103_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='csdn_passworld',
            field=models.CharField(blank=True, help_text='用于模拟登陆csdn', max_length=30, null=True, verbose_name='csdn密码'),
        ),
        migrations.AddField(
            model_name='user',
            name='csdn_username',
            field=models.CharField(blank=True, help_text='用于模拟登陆csdn', max_length=30, null=True, verbose_name='csdn账户'),
        ),
    ]
