# Generated by Django 2.1.3 on 2019-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190223_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
