# Generated by Django 2.1.3 on 2018-11-04 09:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import domain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('p_like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('p_comment', models.IntegerField(default=0, verbose_name='评论数')),
                ('p_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('p_title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('p_img', models.ImageField(blank=True, null=True, upload_to=domain.models.check_img_url, verbose_name='首页图片')),
                ('p_isdelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('p_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章发布者')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'db_table': 'tb_pager',
            },
        ),
    ]
