# Generated by Django 2.1.3 on 2018-11-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20181104_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pager',
            name='p_top',
            field=models.SmallIntegerField(choices=[(0, '不置顶'), (1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=0, verbose_name='首页轮播图（置顶）'),
        ),
    ]
