# Generated by Django 2.1.3 on 2018-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_pager_p_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pager',
            name='p_top',
            field=models.SmallIntegerField(choices=[(0, '不置顶'), (1, '置顶')], default=0, verbose_name='首页轮播图（置顶）'),
        ),
    ]
