# Generated by Django 2.1.3 on 2018-11-18 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0004_auto_20181117_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('p_comment', models.CharField(max_length=500, verbose_name='评论')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Pager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论表',
                'db_table': 'tb_comment',
                'verbose_name_plural': '评论表',
            },
        ),
    ]
