# Generated by Django 2.1.3 on 2018-11-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Comment'),
        ),
    ]
