# Generated by Django 2.1.3 on 2019-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_comment_c_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pager',
            name='p_other_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='博客id'),
        ),
        migrations.AddField(
            model_name='pager',
            name='p_tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='原创 or other'),
        ),
        migrations.AddField(
            model_name='pager',
            name='p_type',
            field=models.SmallIntegerField(choices=[(0, '无平台'), (1, 'csdn'), (2, '简书')], default=0, verbose_name='文章类型（csdn，简书，等）'),
        ),
    ]
