# Generated by Django 2.1.3 on 2019-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_auto_20190115_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='pager',
            name='p_other_link',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='文章链接'),
        ),
    ]
