# Generated by Django 2.1.3 on 2019-02-21 14:05

from django.db import migrations, models
import domain.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_pager_p_other_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('url', models.URLField(max_length=128, verbose_name='url')),
                ('image', models.ImageField(upload_to=domain.models.check_img_url, verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
                'db_table': 'tb_doman_ima',
            },
        ),
    ]
