# Generated by Django 2.1.3 on 2019-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_domanmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='domanmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='pager',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
